Modify ant target -compile-classes
Here 'modulesourcepath' attribute specifies the location of the input source
files for multi module compilation.

This patches the native Java modules: java.base and java.logging

- For gov.nasa.jpf to be able to reference the package java.base/sun.net.www.protocol.http

      --add-exports java.base/sun.net.www.protocol.http=ALL-UNNAMED

      This fixes the error:
      [javac] classes/gov.nasa.jpf/gov/nasa/jpf/CachedROHttpConnection.java:
              error: package sun.net.www.protocol.http is not visible
      [javac] (package sun.net.www.protocol.http is declared in module java.base, which does not export it to unanmed module)

- For java.base to be able to reference classes from the unnamed module (here in our case the package gov.nasa.jpf.annotation)

      --add-reads java.base=ALL-UNNAMED

      This fixes the error:

      [javac] classes/modules/java.base/java/lang/Thread.java:
              error: package gov.nasa.jpf.annotation does not exist

      [javac] classes/modules/java.base/java/io/OutputStreamWriter.java:
              error: package gov.nasa.jpf.vm does not exist

JPF code except for the java model classes is compiled into the default unnamed module.