Use StackWalker instread of sun.misc.SharedSecrets
Use StackWalking API instead of the non-standard sun.misc.SharedSecrets API.

This fixes errors:
    [javac]   error: cannot find symbol
    [javac]   symbol:   class SharedSecrets
    [javac]   location: package sun.misc

    [javac]   error: cannot find symbol
    [javac]   symbol:   class JavaLangAccess
    [javac]   location: class HashedAllocationContext