Refactor references to URLClassPath
sun.misc.URLClassPath has been moved to the internal package:
java.base/jdk.internal.loader.URLClassPath

This fixes:

    [javac] classes/modules/java.base/jdk/internal/misc/JavaNetAccess.java: error: cannot find symbol
    [javac]   URLClassPath getURLClassPath (URLClassLoader ucl);
    [javac]   symbol:   class URLClassPath
    [javac]   location: interface JavaNetAccess