Update ant target -compile-classes
Here 'modulesourcepath' attribute specifies the location of the input source
files for multiple module compilation.

This also patches the native Java modules: java.base and java.logging

- For gov.nasa.jpf module to be albe to reference the package java.base/sun.net.www.protocol.http

      --add-exports java.base/sun.net.www.protocol.http=gov.nasa.jpf

      This fixes the error:
      [javac] classes/gov.nasa.jpf/gov/nasa/jpf/CachedROHttpConnection.java:
              error: package sun.net.www.protocol.http is not visible
      [javac] (package sun.net.www.protocol.http is declared in module java.base, which does not export it to module gov.nasa.jpf)

- For java.base to be able to reference classes from gov.nasa.jpf and unnamed modules (here in our case the package gov.nasa.jpf.annotation)

      --add-reads java.base=gov.nasa.jpf,ALL-UNNAMED

      This fixes the error:

      [javac] classes/java.base/java/lang/Thread.java:
              error: package gov.nasa.jpf.annotation does not exist

      [javac] classes/java.base/java/io/OutputStreamWriter.java:
              error: package gov.nasa.jpf.vm does not exist